// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHmMga3yZD8W55XipZh09afa1VMAoOlGw',
    appId: '1:1006895620015:web:76ba6ae92ec27aeca7195a',
    messagingSenderId: '1006895620015',
    projectId: 'smailo-a832b',
    authDomain: 'smailo-a832b.firebaseapp.com',
    storageBucket: 'smailo-a832b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC72SSuvk55O6mTjHKKXZkZIMWYzubO9Z4',
    appId: '1:1006895620015:android:2367792f24da7326a7195a',
    messagingSenderId: '1006895620015',
    projectId: 'smailo-a832b',
    storageBucket: 'smailo-a832b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD502QFi3N1rQ7JrbS9TGaqseuD5Is4uk8',
    appId: '1:1006895620015:ios:a2a9f72ca0f9dbf3a7195a',
    messagingSenderId: '1006895620015',
    projectId: 'smailo-a832b',
    storageBucket: 'smailo-a832b.appspot.com',
    iosBundleId: 'com.example.smailo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD502QFi3N1rQ7JrbS9TGaqseuD5Is4uk8',
    appId: '1:1006895620015:ios:a2a9f72ca0f9dbf3a7195a',
    messagingSenderId: '1006895620015',
    projectId: 'smailo-a832b',
    storageBucket: 'smailo-a832b.appspot.com',
    iosBundleId: 'com.example.smailo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHmMga3yZD8W55XipZh09afa1VMAoOlGw',
    appId: '1:1006895620015:web:243cf3e805afcfaea7195a',
    messagingSenderId: '1006895620015',
    projectId: 'smailo-a832b',
    authDomain: 'smailo-a832b.firebaseapp.com',
    storageBucket: 'smailo-a832b.appspot.com',
  );
}
